[build]
  base = "."
  command = "NODE_ENV=production ./node_modules/.bin/ng build --prod"
  commandOrigin = "config"
  publish = "dist/dev_Portfolio"
  publishOrigin = "config"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
